# NUMPY est une bibliothete python utiliser pour les operations dans les tableaux elle proposes des fonctions pour travailler sur lalgebre lineaire et la transformee de fourrier 

In [1]:
#importation de numpy 

import numpy #cette methode fonctionne aussi parfaitement 
import numpy as np #cette methode marche pour l'utiliser comme np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#pour voir la version de numpy
print(np.__version__)

1.26.0


In [4]:
#on peut utiliser les tuples pour creer un tableau avec les numpys
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [5]:
#les tableaux 0-D
import numpy as np

arr0 = np.array(42)

print(arr0)

42


In [6]:
#les tableaux a 1-D
#cet a dire les tableaux unidimentionnels

import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [9]:
#les tableaux a 2-D
#cet a dire les tableaux bidimentionnels

import numpy as np
arr2 = np.array([[1,2,3,4],[4,5,6,9]])
print(arr2)

[[1 2 3 4]
 [4 5 6 9]]


In [14]:
#les tableaux a 3-D
#cet a dire les tableaux tridimentionnels

import numpy as np
arr3 = np.array([ [ [1,2,3],[4,5,6] ], [ [1,2,3],[4,5,6] ] ])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
#pour verifier la dimension d'un tableau
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [19]:
#quand nous creons nous pouvons donner la dimension en utilisant ndmin
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('la dimension est de ',arr.ndim)

[[[[[1 2 3 4]]]]]
la dimension est de  5


In [21]:
#indexes les elements d'un tableau

import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr[1])
print(arr[1] + arr[2])

2
5


In [26]:
#indexes les elements d'un tableau a deux dimensions
import numpy as np
arr = np.array([[1,2,3,4],[4,8,7,6]])
print('affiche le deuxiemen elements tu premier tableaux: ',arr[0,1])

affiche le deuxiemen elements tu premier tableaux:  2


In [27]:
#indexes les elements d'un tableau a trois dimensions

import numpy as np
arr = np.array([ [ [1,2,3,4],[5,6,7,8] ],[ [4,3,2,1],[9,8,7,6] ] ])
print("accede au troisiemes elements du deuxieme tableaux du premier tableau: ",arr[0,1,2])

accede au troisiemes elements du deuxieme tableaux du premier tableau:  7


In [28]:
#indexation negative 
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## decoupage de tableau 

In [29]:
#on effectue le decoupage de ceci
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [30]:
#ici on effectue les sauts de deux 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])#on part de 1 jusqua 5 maintenant apres l'element a l'index 1 on prend par pat de deux

[2 4]


In [31]:
#on prend tous les elements du tableaux mais en pats de deux
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [32]:
#cet a dire a partir du tableau deux prend le deuxieme element exclu le 4eme
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [41]:
#a partir des deux element prend le troisieme element de chacun
import numpy as np

arr = np.array([ [1,2,3,4],[5,6,7,8] ])
print(arr[0:2, 2])

[3 7]


In [46]:
#cela veut dire a partir des deux tableau effectue une tranche des deux elemets de 1 au 3ene car le 4ene est exclus
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#les types de donnes utilises par numpy et leurs abbreviations

i- entier
b- booléen
u- entier non signé
f- flotter
c- flotteur complexe
m- delta de temps
M- dateheure
O- objet
S- chaîne
U- chaîne Unicode
V- morceau de mémoire fixe pour un autre type (void)

In [47]:
#dtype est une proprieter en numpy qui donne le type de tableau
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [48]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [49]:
#ici on peut precicer le type de donnee attendu
import numpy as np

arr=np.array([1,2,3,4],dtype="S")

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [50]:
#creer un entier de 4 octets
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [52]:
#Conversion du type de données sur des tableaux existants on utilise astype

import numpy as np
arr = np.array([1.2,2.5,3.6,4.8,5.9])
newarr= arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [53]:
#conversion en utilisant le mot cle int

import numpy as np
arr = np.array([1.9,2.8,3.6,4.3])
newarr2 = arr.astype(int)
print(newarr2)
print(newarr2.dtype)

[1 2 3 4]
int32


La différence entre copier et afficher
La principale différence entre une copie et une vue d'un tableau est que la copie est un nouveau tableau et que la vue est simplement une vue du tableau d'origine.

La copie est propriétaire des données et toute modification apportée à la copie n'affectera pas le tableau d'origine, et toute modification apportée au tableau d'origine n'affectera pas la copie.

La vue n'est pas propriétaire des données et toute modification apportée à la vue affectera le tableau d'origine, et toute modification apportée au tableau d'origine affectera la vue.

In [55]:
#copier un tableau

import numpy as np

arr = np.array([1,2,3,4])

arr2 = arr.copy()

print(arr)
print(arr2)

[1 2 3 4]
[1 2 3 4]


In [56]:
import numpy as np
arr = np.array([1,2,3,4])
x = arr.view()
arr[0] = 42

print(x)
print(arr)

[42  2  3  4]
[42  2  3  4]


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [58]:
#mprimez la valeur de l'attribut de base pour vérifier si un tableau possède ses données ou non
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [59]:
#on utilise shape pour voir lindex et le nombre delement dun tableau qui est renvoyer sous form de tuple exemple

import numpy as np

arr = np.array([ [1,2,3,4],[5,6,7,8] ])
print(arr.shape)#L'exemple ci-dessus renvoie (2, 4), ce qui signifie que le tableau a 2 dimensions, 
#où la première dimension a 2 éléments et la seconde en a 4.

(2, 4)


In [62]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr.shape)
print(arr.ndim)

(1, 1, 1, 1, 4)
5


In [63]:
#reshape est utiliser pour donner une nouvelle dimension a un tableau deja creer

In [64]:
import numpy as np
arr = np.array([2,3,4,5,6,7,8,9,1,23,45,67])
newaray= arr.reshape(4,3)
print(newaray)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9  1]
 [23 45 67]]


In [65]:
#parcourir les elements d'un tableau
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [66]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [69]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [73]:
#parcourir le tableau a chaque fois est tres fatiguant du coup il est mieux dutiliser la fonction nditer qui nous permet
#de le faire sur des dimension avancer
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8


In [74]:
#lorsquon fait un iteration on peut egalement changer le type de donnee attendu et cela nest pas changer dans le tableau mais 
#dans un espace appeller tampon on procede comme suite

import numpy as np
arr = np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [78]:
import numpy as np

arr = np.array([ [1,2,3,8],[4,5,6,7] ])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6


In [81]:
#parfois nous avons besoin de lindex pour effectuer notre enumeartion on va don 
import numpy as np

arr = np.array([1,2,3])

for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [82]:
#tableau a deux dimension
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [86]:
#la concatenation avec les numpy
import numpy as np

arr1 = np.array([1,2,3,4,5])

arr2 = np.array([6,7,8,9,10])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [87]:
#concatener un tableau a deux dimension
import numpy as np
arr1 = np.array([ [1,2],[3,4] ])
arr2 = np.array([ [5,6],[7,8] ])

arr3 = np.concatenate((arr1,arr2),axis=1) #pour mettre chaque premier tableau de chaque dimension entete

print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


In [90]:
#concatenation en utilisant stack

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.stack((arr1,arr2),axis=1)
print(arr3)

[[1 4]
 [2 5]
 [3 6]]


In [93]:
#concatenation en utilisant hstack sur une seule ligne

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [94]:
#Empilement le long des colonnes vstack

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.vstack((arr1,arr2))

print(arr3)

[[1 2 3]
 [4 5 6]]


In [95]:
#Empilage le long de la hauteur (profondeur) dstack
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.dstack((arr1,arr2))

print(arr3)

[[[1 4]
  [2 5]
  [3 6]]]


In [97]:
#la division donc fraction dun tableau
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8])

arr2 = np.array_split(arr,3)

print(arr2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]


In [98]:
#on peut diviser et y acceder  morceau par morceau

import numpy as np

arr1 = np.array([1,2,3,4,5,6])

arr2=np.array_split(arr1,3)
print(arr2[0])
print(arr2[1])
print(arr2[2])

[1 2]
[3 4]
[5 6]


In [99]:
#decoupage dun tableau a deux dimension

import numpy as np
arr1 = np.array([ [1,2],[3,4],[5,6],[7,8],[9,8],[7,6],[5,4] ])
arr2= np.array_split(arr1,3)
print(arr2)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[7, 8],
       [9, 8]]), array([[7, 6],
       [5, 4]])]


In [100]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [101]:
#on peut preciser la ligne 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [103]:
#on peut recharcher des valeur avec les index a savoir

import numpy as np

arr = np.array([1,5,4,3,8,4,4])

x = np.where(arr == 4)

print(x)#Ce qui signifie que la valeur 4 est présente aux index 2, 5 et 6.

(array([2, 5, 6], dtype=int64),)


In [104]:
#on recherhce des valeur impaire

import numpy as np

arr = np.array([3,5,6,4,7,8,9,5,23,14,12])

arr1 = np.where(arr%2 == 1)
print(arr1)

(array([0, 1, 4, 6, 7, 8], dtype=int64),)


In [106]:
#Il existe une méthode appelée searchsorted()qui effectue une recherche binaire dans le tableau 
#et renvoie l'index où la valeur spécifiée serait insérée pour maintenir l'ordre de recherche.

import numpy as np
arr = np.array([4,5,6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

3


In [107]:
import numpy as np
arr = np.array([4,5,6,7,8,9])
x = np.searchsorted(arr,7,side="right")
print(x)

4


In [108]:
#si on veut specifier de multiple donner

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr,[2,4,6])

print(x)

[1 2 3]


In [109]:
#trier les elements d'un tableau

import numpy as np

arr = np.array([5,3,6,8])

newarr = np.sort(arr)
print(newarr)

[3 5 6 8]


In [110]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [112]:
#trier un element dans unn tableau 
import numpy as np

arr= np.array([42,56,32,85])
x=[True, False, True, False]
newarr = arr[x]
print(newarr)

[42 32]


In [114]:
#ici on va utiliser le tri avec condition a savoir
import numpy as np
arr= np.array([42,56,32,85])
filter_arr = []
for element in arr:
    if element > 42 :
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True]
[56 85]


In [116]:
#ON  verifie les element paire de notre tableau
import numpy as np
arr = np.array([42,56,32,85])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
result = arr[filter_arr]
print(filter_arr)
print(result)

[True, True, True, False]
[42 56 32]


In [118]:
#sans utiliser les condition maintenant on aura
import numpy as np
arr = np.array([1,3,2,6,5,7,8])
filter_arr = arr > 3
result = arr[filter_arr]
print(result)

[6 5 7 8]


In [119]:
import numpy as np
arr = np.array([1,3,2,6,5,7,8])
filter_arr = arr % 2 == 0
result = arr[filter_arr]
print(result)

[2 6 8]
